"""Provenance & disclosure for generated datasets.

Every dataset carries an auditable manifest — tool/version, model, seed, config,
and a content hash — plus an explicit synthetic-data disclaimer, so the output
can be traced and can never be mistaken for real survey responses.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from typing import Any, Optional

APP_VERSION = "1.1.0"

DISCLAIMER = (
    "SYNTHETIC DATA — every response here was generated by an AI persona, not a "
    "real respondent. Do not present it as real survey data without clear "
    "disclosure."
)


def _config_hash(config: dict) -> str:
    """Stable hash of the study configuration (order-independent)."""
    blob = json.dumps(config or {}, sort_keys=True, default=str)
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()[:16]


def build_manifest(
    dataset: Any,
    schema: Any,
    settings: Any,
    study_config: Optional[dict] = None,
    seed: Optional[int] = None,
) -> dict:
    """Assemble the provenance manifest for a completed dataset."""
    provider = getattr(settings, "llm_provider", "unknown")
    model = getattr(settings, f"{provider}_model", "unknown")
    responses = getattr(dataset, "responses", [])
    generated = sum(1 for r in responses if getattr(r, "generation_success", False))
    waves = sorted({getattr(r, "wave", 1) for r in responses})
    variants = sorted({r.stimulus_variant for r in responses if getattr(r, "stimulus_variant", None)})

    manifest = {
        "tool": "SynthSurvey",
        "version": APP_VERSION,
        "disclaimer": DISCLAIMER,
        "generated_at": getattr(dataset, "generation_completed", None)
        or datetime.now(timezone.utc).isoformat(),
        "form": {
            "title": getattr(schema, "form_title", None),
            "url": getattr(schema, "form_url", None),
            "total_questions": getattr(schema, "total_questions", None),
            "parse_method": getattr(schema, "parse_method", "structured"),
        },
        "generation": {
            "provider": provider,
            "model": model,
            "temperature": getattr(settings, "temperature", None),
            "seed": seed if seed is not None else getattr(settings, "seed", None),
            "concurrency": getattr(settings, "concurrency", None),
        },
        "counts": {
            "total_responses": len(responses),
            "successful": generated,
            "failed": len(responses) - generated,
            "waves": waves,
            "stimulus_variants": variants,
        },
        "study_config": study_config or {},
        "config_hash": _config_hash(study_config or {}),
        "reproducibility_note": (
            "The seed makes persona/variant assignment and trait sampling "
            "reproducible. LLM answers still vary run-to-run unless temperature "
            "is 0 and the provider is deterministic."
        ),
    }
    return manifest


def manifest_to_bytes(manifest: dict) -> bytes:
    return json.dumps(manifest, indent=2, ensure_ascii=False).encode("utf-8")
